version: '3.3'
services:
  mongo:
    image: 'mongo:4.4.14'
    container_name: "metrics_mongo"
    restart: unless-stopped
    command: mongod --auth
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: metrics
